<html itemscope itemtype="http://schema.org/Product">
	<head>
		<meta itemprop="name" content="Hoborg Labs Dashboard">
		<meta itemprop="description" content="Quick and easy way to add dynamic dashboard to your project!">

		<?php if ('production' == APP_ENV) : ?>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-26727070-1']);
			_gaq.push(['_trackPageview']);
	
			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();
	
			(function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			})();
		</script>
		<?php endif; ?>
		<link href="/styles/css/bootstrap.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/css/layout.css" media="all" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<a href="http://github.com/hoborglabs/Dashboard"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://a248.e.akamai.net/assets.github.com/img/71eeaab9d563c2b3c590319b398dd35683265e85/687474703a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677261795f3664366436642e706e67" alt="Fork me on GitHub"></a>

		<div id="header" class="container">
			<div class="row">
				<div class="span4">
					<h1>HoborgLabs Dashoboard</h1>
				</div>
				<div class="span12">
					<div style="background-color: #666; color: #FFF; padding: 4px 10px; text-align: center" class="span1 offset10">BETA</div>
					<ul class="tabs" style="margin-top: 30px;">
						<?php
						if (!isset($active_link)) {
							$active_link = '/';
						}
						$links = array(
							'/' => 'Home',
							'/doc' => 'Documentation',
							'/demo' => 'Demo',
						);
						?>
						<?php foreach ($links as $href => $title) : $class = ''; ?>
							<?php if ($active_link == $href) { $class = 'active'; } ?>
							<li class="<?php echo $class; ?>">
								<a href="<?php echo $href; ?>"><?php echo $title; ?></a>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>

		<div id="body" class="container">
			<?php echo $body; ?>
		</div>

		<div id="footer" class="container">
			<p>power by <a href="http://hoborglabs.com">hoborglabs</a></p>
		</div>
	</body>
</html>
