<html itemscope itemtype="http://schema.org/Product">
	<head>
		<meta itemprop="name" content="Hoborg Labs Dashboard">
		<meta itemprop="description" content="Quick and easy way to add dynamic dashboard to your project!">

		<?php if ('production' == APP_ENV) : ?>
		<script type="text/javascript">
			var _gaq = _gaq || [];
			_gaq.push(['_setAccount', 'UA-26727070-1']);
			_gaq.push(['_trackPageview']);

			(function() {
				var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
				ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
			})();

			(function() {
				var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
				po.src = 'https://apis.google.com/js/plusone.js';
				var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
			})();
		</script>
		<?php endif; ?>

		<link href="/styles/css/common.css" media="all" rel="stylesheet" type="text/css" />
		<link href="/styles/css/layout.css" media="all" rel="stylesheet" type="text/css" />
		<meta name="viewport" content="initial-scale = 1.0,maximum-scale = 1.0" />

		<link href="/dashboard/styles/templates/hoborg/css/dashboard.css" media="all" rel="stylesheet" type="text/css" />
		<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
		<script type="text/javascript" src="/dashboard/js/jquery/jquery.mustache.js"></script>
		<script type="text/javascript" src="/dashboard/js/jquery/jquery.masonry.min.js"></script>
		<script type="text/javascript" src="/dashboard/js/hoborg/bus.js"></script>
		<script type="text/javascript" src="/dashboard/js/hoborg/jquery.widgetManager.js"></script>

		<script type="text/javascript">
		$(document).ready(function() {
			// distribute widgets on the screen.
			$('.dashboard.container').masonry({
				itemSelector: '.widget',
				columnWidth: 10,
				isFitWidth: true,
				isAnimated: true
			});

			var hoborg_tpl = <?php echo json_encode(file_get_contents(__DIR__ . '/hoborg-widget.jhtml')); ?>;

			$('.dashboard.container').widgetManager({
				url: '/demo/index.php',
				conf: 'demo',
				callback: function(widget) { $('.dashboard.container').masonry('reload'); },
				template: hoborg_tpl
			});

			var widgets = [
			<?php $coma = '' ?>
			<?php foreach ($this->widgets as $index => & $widget) : ?>
				<?php echo $coma . $widget->getJson() . "\n"; $coma = ','; ?>
			<?php endforeach; unset($widget); ?>
			];

			$('.dashboard.container').widgetManager('addWidgets', widgets);
			$('.dashboard.container').widgetManager('start');

		});
		</script>

		<?php echo $head; ?>

		<style>
			[class*="span"]:first-child {
				margin-left: 10px;
			}
		</style>
	</head>
	<body>
		<div id="header" class="container">
			<div class="row">
				<div class="beta">v. BETA</div>

                <div class="logo">
                    <h1><b>H</b>oborg<b>L</b>abs <span>Dashoboard</span></h1>
                </div>

                <div class="quicklinks">
                    <ul>
                        <li class="trello"><a href="https://trello.com/board/dashboard/4ea7062eaed5f360a418c6f5">trello board</a></li>
                        <li class="github"><a href="http://github.com/hoborglabs/Dashboard">view on github</a></li>
                        <li class="php"><a href="/downloads/dashboard.phar">dashboard.phar</a></li>
                    </ul>
                </div>

				<div class="navigation">
					<ul class="tabs" style="margin-top: 30px;">
						<?php
						if (!isset($active_link)) {
							$active_link = '/demo';
						}
						$links = array(
							'/' => 'Home',
							'/doc' => 'Documentation',
							'/demo' => 'Demo',
						);
						?>
						<?php foreach ($links as $href => $title) : $class = ''; ?>
							<?php if ($active_link == $href) { $class = 'active'; } ?>
							<li class="<?php echo $class; ?>">
								<a href="<?php echo $href; ?>"><?php echo $title; ?></a>
							</li>
						<?php endforeach; ?>
					</ul>
				</div>
			</div>
		</div>

<div class="container">
            <div class="row">
                <div class="span16"><p><b>Resize</b> your browser window, and see how widgets adjusts to your screen size.</p>
                </div>
            </div>
        </div>

		<div id="body" class="dashboard container">

		</div>

		<div id="footer" class="container">
			<p>power by <a href="http://hoborglabs.com">hoborglabs</a></p>
		</div>
	</body>
</html>
